---
- hosts: all
  become: true
  tasks:
    - name: Ensure apt key for hashicorp is present
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
      become: true

    - name: Ensure repository for Hashicorp is present.
      ansible.builtin.apt_repository:
        repo: deb https://apt.releases.hashicorp.com {{ ansible_lsb.codename }}  main
        state: present
      become: true

    - name: Ensure Vault is installed
      ansible.builtin.apt:
        name:
          - vault
        update_cache: yes

    - name: Ensure Vault configuration file is present
      ansible.builtin.copy:
        src: ./files/vault.hcl
        dest: /etc/vault.d/vault.hcl
        owner: vault
        group: vault
        mode: '0644'
        backup: true
      notify:
      - Restart Vault

    - name: Ensure Systemd Service file definition is present
      ansible.builtin.copy:
        src: ./files/vault.service
        dest: /lib/systemd/system/vault.service
        owner: root
        group: root
        mode: '0644'
        backup: true
      notify:
      - Restart Vault

    - name: Ensure Vault Service is enabled
      ansible.builtin.service:
        name: vault
        enabled: true
        state: started

  handlers:
    - name: Restart Vault
      ansible.builtin.service:
        name: vault
        state: restarted
